antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'tracing'
site:
  title: Micrometer Tracing
  url: https://docs.micrometer.io/tracing/reference/
  robots: allow
content:
  sources:
    - url: https://github.com/micrometer-metrics/tracing
      # Refname matching:
      # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches: [ main ]
      # 1.[3-9][0-9].[0-9] RC, M and GA (e.g. 1.3.1, 1.44.6)
      # 1.2[0-9].[0-9] RC, M and GA without 1.2.0-M[0-3] (e.g. 1.2.0-M4, 1.2.1, 1.20.0)
      tags: [ 'v({1..9}).({3..9})({0..9}).+({0..9})?(-{RC,M}+({0..9}))', 'v1.2{0..9}+.({0..9})?(-{RC,M}+({0..9}))', '!v1.2.0-M({0..3}))' ]
      start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/micrometer
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
  sourcemap: true
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/rwinch/antora-ui-micrometer/releases/download/latest/ui-bundle.zip
    snapshot: true
